spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 5
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      groups-id: ${SYSTEM_INSTANCE:666}
    properties:
      spring:
        json:
          trusted:
            packages: '*'
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:192.168.0.32}
      database: ${REDIS_DB:0}
      password: ${REDIS_PASS:root}
    mongodb:
      host: ${MONGODB_HOST:192.168.0.32}
      database: doctors_db
      port: ${MONGODB_PORT:27017}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
    org.springframework.web: info
    br.com.avf.services.medical.doctors: debug
  file:
    name: ./logs/${spring.application.name}.log
springdoc:
  api-docs:
    groups:
      enabled: 'true'
    path: /doc/doctors/v3/api-documents
  swagger-ui:
    enabled: 'true'
    path: /doc/doctors/v1/api.html
api:
  version: v1
  description: Description here
  url:
    homologation: http://${HOMOLOGATION_SERVER:172.30.1.24}:${HOMOLOGATION_PORT:8081}
    production: ${PRODUCTION_URI:http://${spring.application.name}.jtech.com.br}